version: "3.8"

services:
  api:
    build: .
    container_name: go-api
    environment:
      SRV_MODE: "production"
      SRV_PORT: "8080"
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_NAME: pin_db
      DB_PORT: 5432
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: pin_db
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend:
    driver: bridge